// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package item_catalog_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ItemClient is the client API for Item service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ItemClient interface {
	// CreatesTestItems
	CreateTestItems(ctx context.Context, in *CreateTestItemsRequest, opts ...grpc.CallOption) (*CreateTestItemsReply, error)
}

type itemClient struct {
	cc grpc.ClientConnInterface
}

func NewItemClient(cc grpc.ClientConnInterface) ItemClient {
	return &itemClient{cc}
}

func (c *itemClient) CreateTestItems(ctx context.Context, in *CreateTestItemsRequest, opts ...grpc.CallOption) (*CreateTestItemsReply, error) {
	out := new(CreateTestItemsReply)
	err := c.cc.Invoke(ctx, "/item_catalog_service.Item/CreateTestItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemServer is the server API for Item service.
// All implementations must embed UnimplementedItemServer
// for forward compatibility
type ItemServer interface {
	// CreatesTestItems
	CreateTestItems(context.Context, *CreateTestItemsRequest) (*CreateTestItemsReply, error)
	mustEmbedUnimplementedItemServer()
}

// UnimplementedItemServer must be embedded to have forward compatible implementations.
type UnimplementedItemServer struct {
}

func (UnimplementedItemServer) CreateTestItems(context.Context, *CreateTestItemsRequest) (*CreateTestItemsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTestItems not implemented")
}
func (UnimplementedItemServer) mustEmbedUnimplementedItemServer() {}

// UnsafeItemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ItemServer will
// result in compilation errors.
type UnsafeItemServer interface {
	mustEmbedUnimplementedItemServer()
}

func RegisterItemServer(s grpc.ServiceRegistrar, srv ItemServer) {
	s.RegisterService(&_Item_serviceDesc, srv)
}

func _Item_CreateTestItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTestItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServer).CreateTestItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item_catalog_service.Item/CreateTestItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServer).CreateTestItems(ctx, req.(*CreateTestItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Item_serviceDesc = grpc.ServiceDesc{
	ServiceName: "item_catalog_service.Item",
	HandlerType: (*ItemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTestItems",
			Handler:    _Item_CreateTestItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item_catalog_service/item.proto",
}
