// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item_catalog_service/item.proto

package item_catalog_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateTestItemsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTestItemsRequest) Reset()         { *m = CreateTestItemsRequest{} }
func (m *CreateTestItemsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTestItemsRequest) ProtoMessage()    {}
func (*CreateTestItemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed8038625aa18fce, []int{0}
}

func (m *CreateTestItemsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTestItemsRequest.Unmarshal(m, b)
}
func (m *CreateTestItemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTestItemsRequest.Marshal(b, m, deterministic)
}
func (m *CreateTestItemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTestItemsRequest.Merge(m, src)
}
func (m *CreateTestItemsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTestItemsRequest.Size(m)
}
func (m *CreateTestItemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTestItemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTestItemsRequest proto.InternalMessageInfo

type CreateTestItemsReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTestItemsReply) Reset()         { *m = CreateTestItemsReply{} }
func (m *CreateTestItemsReply) String() string { return proto.CompactTextString(m) }
func (*CreateTestItemsReply) ProtoMessage()    {}
func (*CreateTestItemsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed8038625aa18fce, []int{1}
}

func (m *CreateTestItemsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTestItemsReply.Unmarshal(m, b)
}
func (m *CreateTestItemsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTestItemsReply.Marshal(b, m, deterministic)
}
func (m *CreateTestItemsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTestItemsReply.Merge(m, src)
}
func (m *CreateTestItemsReply) XXX_Size() int {
	return xxx_messageInfo_CreateTestItemsReply.Size(m)
}
func (m *CreateTestItemsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTestItemsReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTestItemsReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateTestItemsRequest)(nil), "item_catalog_service.CreateTestItemsRequest")
	proto.RegisterType((*CreateTestItemsReply)(nil), "item_catalog_service.CreateTestItemsReply")
}

func init() { proto.RegisterFile("item_catalog_service/item.proto", fileDescriptor_ed8038625aa18fce) }

var fileDescriptor_ed8038625aa18fce = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcf, 0x2c, 0x49, 0xcd,
	0x8d, 0x4f, 0x4e, 0x2c, 0x49, 0xcc, 0xc9, 0x4f, 0x8f, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e,
	0xd5, 0x07, 0x09, 0xea, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x89, 0x60, 0x53, 0xa0, 0x24, 0xc1,
	0x25, 0xe6, 0x5c, 0x94, 0x9a, 0x58, 0x92, 0x1a, 0x92, 0x5a, 0x5c, 0xe2, 0x59, 0x92, 0x9a, 0x5b,
	0x1c, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0xa2, 0x24, 0xc6, 0x25, 0x82, 0x21, 0x53, 0x90, 0x53,
	0x69, 0x54, 0xcc, 0xc5, 0x02, 0xe2, 0x09, 0x65, 0x73, 0xf1, 0xa3, 0xc9, 0x0b, 0xe9, 0xe8, 0x61,
	0xb3, 0x43, 0x0f, 0xbb, 0x05, 0x52, 0x5a, 0x44, 0xaa, 0x2e, 0xc8, 0xa9, 0x74, 0xb2, 0x8c, 0x12,
	0xd3, 0xb3, 0xc6, 0xa6, 0x7c, 0x15, 0x93, 0x1c, 0x48, 0x99, 0x33, 0x44, 0x34, 0x18, 0x6a, 0x46,
	0x7a, 0x50, 0x80, 0x33, 0x94, 0x9d, 0xc4, 0x06, 0xf6, 0xbe, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0xe1, 0x7a, 0x52, 0xbb, 0x21, 0x01, 0x00, 0x00,
}
