// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_service/user.proto

package user_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TokenClaims struct {
	IsAdmin              bool     `protobuf:"varint,1,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Expires              int64    `protobuf:"varint,3,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenClaims) Reset()         { *m = TokenClaims{} }
func (m *TokenClaims) String() string { return proto.CompactTextString(m) }
func (*TokenClaims) ProtoMessage()    {}
func (*TokenClaims) Descriptor() ([]byte, []int) {
	return fileDescriptor_749038872b9165fb, []int{0}
}

func (m *TokenClaims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenClaims.Unmarshal(m, b)
}
func (m *TokenClaims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenClaims.Marshal(b, m, deterministic)
}
func (m *TokenClaims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenClaims.Merge(m, src)
}
func (m *TokenClaims) XXX_Size() int {
	return xxx_messageInfo_TokenClaims.Size(m)
}
func (m *TokenClaims) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenClaims.DiscardUnknown(m)
}

var xxx_messageInfo_TokenClaims proto.InternalMessageInfo

func (m *TokenClaims) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *TokenClaims) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TokenClaims) GetExpires() int64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

type CreateUserRequest struct {
	Claims               *TokenClaims `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	IsAdmin              bool         `protobuf:"varint,2,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	Username             string       `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string       `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string       `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_749038872b9165fb, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetClaims() *TokenClaims {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *CreateUserRequest) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_749038872b9165fb, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetUserRequest struct {
	Claims               *TokenClaims `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	Id                   string       `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_749038872b9165fb, []int{3}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetClaims() *TokenClaims {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetUserResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_749038872b9165fb, []int{4}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetUserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AuthRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_749038872b9165fb, []int{5}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_749038872b9165fb, []int{6}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidateTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateTokenRequest) Reset()         { *m = ValidateTokenRequest{} }
func (m *ValidateTokenRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateTokenRequest) ProtoMessage()    {}
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_749038872b9165fb, []int{7}
}

func (m *ValidateTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateTokenRequest.Unmarshal(m, b)
}
func (m *ValidateTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateTokenRequest.Marshal(b, m, deterministic)
}
func (m *ValidateTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateTokenRequest.Merge(m, src)
}
func (m *ValidateTokenRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateTokenRequest.Size(m)
}
func (m *ValidateTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateTokenRequest proto.InternalMessageInfo

func (m *ValidateTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_749038872b9165fb, []int{8}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*TokenClaims)(nil), "user_service.TokenClaims")
	proto.RegisterType((*CreateUserRequest)(nil), "user_service.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "user_service.CreateUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "user_service.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "user_service.GetUserResponse")
	proto.RegisterType((*AuthRequest)(nil), "user_service.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "user_service.AuthResponse")
	proto.RegisterType((*ValidateTokenRequest)(nil), "user_service.ValidateTokenRequest")
	proto.RegisterType((*Error)(nil), "user_service.Error")
}

func init() { proto.RegisterFile("user_service/user.proto", fileDescriptor_749038872b9165fb) }

var fileDescriptor_749038872b9165fb = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0xdd, 0xa4, 0x4d, 0xd9, 0x4e, 0x96, 0x02, 0xa3, 0x0a, 0x42, 0x04, 0x22, 0xb2, 0x38, 0xf4,
	0x80, 0x8a, 0x58, 0xb8, 0x21, 0x84, 0x96, 0x65, 0xb5, 0xe2, 0x80, 0x84, 0x52, 0x40, 0x82, 0x0b,
	0x0a, 0xf5, 0x48, 0x58, 0xb4, 0x75, 0xb0, 0x5d, 0xe0, 0xab, 0xb8, 0xf1, 0x7f, 0xc8, 0x76, 0x13,
	0x39, 0xa5, 0x39, 0xed, 0xad, 0xaf, 0x33, 0xf3, 0xe6, 0xbd, 0xe7, 0x51, 0xe0, 0xce, 0x56, 0x93,
	0xfa, 0xa2, 0x49, 0xfd, 0x14, 0x4b, 0x7a, 0x6c, 0xc1, 0xbc, 0x56, 0xd2, 0x48, 0x3c, 0x09, 0x0b,
	0xec, 0x13, 0xa4, 0xef, 0xe5, 0x77, 0xda, 0x9c, 0xaf, 0x2a, 0xb1, 0xd6, 0x98, 0xc1, 0x35, 0xa1,
	0xcf, 0xf8, 0x5a, 0x6c, 0xb2, 0xa8, 0x88, 0x66, 0xc7, 0x65, 0x03, 0xf1, 0x36, 0x8c, 0xec, 0xe0,
	0x1b, 0x9e, 0xc5, 0x45, 0x34, 0x1b, 0x97, 0x3b, 0x64, 0x27, 0xe8, 0x77, 0x2d, 0x14, 0xe9, 0x6c,
	0x50, 0x44, 0xb3, 0x41, 0xd9, 0x40, 0xf6, 0x27, 0x82, 0x5b, 0xe7, 0x8a, 0x2a, 0x43, 0x1f, 0x34,
	0xa9, 0x92, 0x7e, 0x6c, 0x49, 0x1b, 0x7c, 0x02, 0xa3, 0xa5, 0xdb, 0xe5, 0x16, 0xa4, 0xa7, 0x77,
	0xe7, 0xa1, 0x9e, 0x79, 0x20, 0xa6, 0xdc, 0x35, 0x86, 0xa2, 0xe2, 0xae, 0xa8, 0x1c, 0x8e, 0xed,
	0xf4, 0xa6, 0x5a, 0x93, 0xdb, 0x3e, 0x2e, 0x5b, 0x8c, 0x53, 0x48, 0x68, 0x5d, 0x89, 0x55, 0x36,
	0x74, 0x05, 0x0f, 0xec, 0x44, 0x5d, 0x69, 0xfd, 0x4b, 0x2a, 0x9e, 0x25, 0x7e, 0xa2, 0xc1, 0xec,
	0x21, 0x60, 0xa8, 0x57, 0xd7, 0x72, 0xa3, 0x09, 0x27, 0x10, 0x0b, 0xee, 0xc4, 0x8e, 0xcb, 0x58,
	0x70, 0xb6, 0x80, 0xc9, 0x25, 0x99, 0x2b, 0x5a, 0xf2, 0xa4, 0x71, 0x40, 0x7a, 0xa3, 0x25, 0x3d,
	0xbc, 0xb7, 0xe3, 0x35, 0xee, 0xf3, 0x3a, 0x08, 0xbc, 0xb2, 0x0b, 0x48, 0xcf, 0xb6, 0xe6, 0x5b,
	0x23, 0x33, 0x24, 0x88, 0xf6, 0x08, 0xc2, 0x58, 0xe2, 0xbd, 0x58, 0x9e, 0xc1, 0x89, 0xa7, 0xe9,
	0x11, 0x36, 0x85, 0xc4, 0x58, 0x8b, 0xbb, 0x41, 0x0f, 0xd8, 0x23, 0x98, 0x7e, 0xac, 0x56, 0x82,
	0x57, 0x86, 0x5c, 0x00, 0x8d, 0x8a, 0xb6, 0x3b, 0x0a, 0xbb, 0x5f, 0x40, 0x72, 0xa1, 0x94, 0x54,
	0x88, 0x30, 0x5c, 0x4a, 0xee, 0x05, 0x26, 0xa5, 0xfb, 0x8d, 0x05, 0xa4, 0x9c, 0xf4, 0x52, 0x89,
	0xda, 0x08, 0xd9, 0xac, 0x09, 0xff, 0x3a, 0xfd, 0x1b, 0x43, 0x6a, 0xc3, 0x5b, 0xf8, 0xc8, 0xf1,
	0x2d, 0x8c, 0xfc, 0x4b, 0xe2, 0x83, 0xee, 0x5b, 0xfc, 0x77, 0x8f, 0x79, 0xd1, 0xdf, 0xe0, 0xfd,
	0xb2, 0x23, 0x7c, 0x0d, 0x83, 0x4b, 0x32, 0x78, 0xaf, 0xdb, 0xda, 0xbd, 0x82, 0xfc, 0x7e, 0x4f,
	0xb5, 0x65, 0x79, 0x09, 0x43, 0x9b, 0x23, 0xee, 0x9d, 0x47, 0xf0, 0x44, 0x79, 0x7e, 0xa8, 0xd4,
	0x12, 0xbc, 0x83, 0xeb, 0x9d, 0x48, 0x91, 0x75, 0xdb, 0x0f, 0xe5, 0x9d, 0xf7, 0x1f, 0x23, 0x3b,
	0x7a, 0x75, 0xf3, 0xf3, 0x64, 0xfe, 0x3c, 0xac, 0x7f, 0x1d, 0xb9, 0x8f, 0xc4, 0xd3, 0x7f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x18, 0x48, 0x4d, 0xc6, 0x3f, 0x04, 0x00, 0x00,
}
